#ifndef CONST_H_INCLUDED
#define CONST_H_INCLUDED

#define CONST_H_INCLUDED

#define TRUE 1
#define FALSE 0
#define WINDOW_WIDTH   800
#define  WINDOW_HEIGHT 600
#define  FPS 60
#define FRAME_TARGET_TIME  (1000/FPS)
#endif // CONST_H_INCLUDED
